# https://circleci.com/docs/docker
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/cci/

    steps:
      - checkout

      - run:
          name: Build the image
          command: |
            ci/build

      - run:
          name: Test the image
          command: |
            ci/test

      - deploy:
          name: Deploy from 3.6 branch
          command: |
            if [[ ${CIRCLE_BRANCH} = 3.6 ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              ci/publish
            fi
